version: '3'

services:
  db:
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521"
      - "81:81"
    volumes:
      - "./application_data/db:/opt/h2-data"

  camunda:
    image: camunda/camunda-bpm-platform:wildfly-latest
    env_file:
      - camunda.env
    ports:
      - "8081:8080"
      - "9991:9990"
    depends_on:
      - db

  goofy:
    build: .
    image: brdietdidi/goofy:latest
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - db
